on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Preparar ambiente
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          GIT_ASKPASS: /bin/true
          GIT_AUTHOR_NAME: "kayqueh"
          GIT_AUTHOR_EMAIL: "kayque@brcore.com.br"
          GIT_COMMITTER_NAME: "kayqueh"
          GIT_COMMITTER_EMAIL: "kayque@brcore.com.br"
        run: |
          git clone -b main https://$GITHUB_TOKEN@github.com/kayqueh/populate-app.git ${{ github.workspace }}

      - name: ðŸ— Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: ðŸ— Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: ðŸ“¦ Install dependencies
        run: npm install

      - name: ðŸ— Instalar Boost 1.76
        run: |
          brew uninstall --ignore-dependencies boost || true
          brew install boost@1.76
          echo 'export PATH="/usr/local/opt/boost@1.76/bin:$PATH"' >> $HOME/.bash_profile
          echo 'export LDFLAGS="-L/usr/local/opt/boost@1.76/lib"' >> $HOME/.bash_profile
          echo 'export CPPFLAGS="-I/usr/local/opt/boost@1.76/include"' >> $HOME/.bash_profile
          source $HOME/.bash_profile

      - name: ðŸ“¢ Verificar versÃ£o do Boost
        run: brew info boost

      - name: ðŸš€ Build app
        run: eas build -p ios --profile production --non-interactive --local --clear-cache
        
      - name: Subir IPA para loja
        run: eas submit -p ios --path /Users/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/build-*.ipa --non-interactive
