on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Preparar ambiente
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          GIT_ASKPASS: /bin/true
          GIT_AUTHOR_NAME: "kayqueh"
          GIT_AUTHOR_EMAIL: "kayque@brcore.com.br"
          GIT_COMMITTER_NAME: "kayqueh"
          GIT_COMMITTER_EMAIL: "kayque@brcore.com.br"
        run: |
          git clone -b main https://$GITHUB_TOKEN@github.com/kayqueh/populate-app.git ${{ github.workspace }}

      - name: üèó Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: üèó Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: üì¶ Install dependencies
        run: npm install

      - name: üîç Verificar diret√≥rios antes de alterar boost.podspec
        run: |
          echo "Listando diret√≥rios dentro de ios"
          ls -R node_modules/react-native/third-party-podspecs
          echo "Fim da listagem"
          
      - name: üìù Alterar URL do Boost no boost.podspec
        run: |
          sed -i '' 's|https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.bz2|https://archives.boost.io/release/1.76.0/source/boost_1_76_0.tar.bz2|' ios/node_modules/react-native/third-party-podspecs/boost.podspec


      - name: üöÄ Build app
        run: eas build -p ios --profile production --non-interactive --local --clear-cache
        
      - name: Subir IPA para loja
        run: eas submit -p ios --path /Users/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/build-*.ipa --non-interactive
